// RUN: python3.13 tenstorrent/tools/tt-opt %s -p convert-ttx-to-ttkernel | filecheck %s

builtin.module {
  builtin.module attributes {kernel_type = "compute"} {
    func.func @add_two_int_tiles() {
      %0 = arith.constant 0 : i32
      %cb0 = memref.alloc() : memref<i32>
      memref.store %0, %cb0[] : memref<i32>
      %1 = arith.constant 1 : i32
      %cb1 = memref.alloc() : memref<i32>
      memref.store %1, %cb1[] : memref<i32>
      %2 = arith.constant 16 : i32
      %cb_out = memref.alloc() : memref<i32>
      memref.store %2, %cb_out[] : memref<i32>
      %3 = memref.load %cb0[] : memref<i32>
      %4 = memref.load %cb1[] : memref<i32>
      %5 = memref.load %cb_out[] : memref<i32>
      "comp.binary_op_init_common"(%3, %4, %5) : (i32, i32, i32) -> ()
      %6 = memref.load %cb0[] : memref<i32>
      %7 = memref.load %cb1[] : memref<i32>
      %8 = arith.constant false
      "comp.add_tiles_init"(%6, %7, %8) : (i32, i32, i1) -> ()
      %9 = memref.load %cb0[] : memref<i32>
      %10 = arith.constant 1 : i32
      "cb.wait_front"(%9, %10) : (i32, i32) -> ()
      %11 = memref.load %cb1[] : memref<i32>
      %12 = arith.constant 1 : i32
      "cb.wait_front"(%11, %12) : (i32, i32) -> ()
      "comp.tile_regs_acquire"() : () -> ()
      %13 = memref.load %cb0[] : memref<i32>
      %14 = memref.load %cb1[] : memref<i32>
      %15 = arith.constant 0 : i32
      %16 = arith.constant 0 : i32
      %17 = arith.constant 0 : i32
      "comp.add_tiles"(%13, %14, %15, %16, %17) : (i32, i32, i32, i32, i32) -> ()
      "comp.tile_regs_commit"() : () -> ()
      "comp.tile_regs_wait"() : () -> ()
      %18 = arith.constant 0 : i32
      %19 = memref.load %cb_out[] : memref<i32>
      %20 = arith.constant 0 : i32
      "comp.pack_tile"(%18, %19, %20) <{out_of_order_output = false}> : (i32, i32, i32) -> ()
      "comp.tile_regs_release"() : () -> ()
      %21 = memref.load %cb0[] : memref<i32>
      %22 = arith.constant 1 : i32
      "cb.pop_front"(%21, %22) : (i32, i32) -> ()
      %23 = memref.load %cb1[] : memref<i32>
      %24 = arith.constant 1 : i32
      "cb.pop_front"(%23, %24) : (i32, i32) -> ()
      %25 = memref.load %cb_out[] : memref<i32>
      %26 = arith.constant 1 : i32
      "cb.push_back"(%25, %26) : (i32, i32) -> ()
      func.return
    }
  }
}

// CHECK:      builtin.module {
// CHECK-NEXT:   func.func @"add_two_int_tiles"(%0 : !ttkernel.cb<cb_in0, 0 : i32, memref<8x4x4x1024xf32>, 4096 : i32, 1 : i32>, %1 : !ttkernel.cb<cb_in1, 0 : i32, memref<8x4x4x1024xf32>, 4096 : i32, 1 : i32>, %2 : !ttkernel.cb<cb_in2, 0 : i32, memref<8x4x4x1024xf32>, 4096 : i32, 1 : i32>) {
// CHECK-NEXT:     "ttkernel.binary_op_init_common"(%0, %1, %2) : (!ttkernel.cb<cb_in0, 0 : i32, memref<8x4x4x1024xf32>, 4096 : i32, 1 : i32>, !ttkernel.cb<cb_in1, 0 : i32, memref<8x4x4x1024xf32>, 4096 : i32, 1 : i32>, !ttkernel.cb<cb_in2, 0 : i32, memref<8x4x4x1024xf32>, 4096 : i32, 1 : i32>) -> ()
// CHECK-NEXT:     %3 = arith.constant false
// CHECK-NEXT:     "ttkernel.add_tiles_init"(%0, %1) : (!ttkernel.cb<cb_in0, 0 : i32, memref<8x4x4x1024xf32>, 4096 : i32, 1 : i32>, !ttkernel.cb<cb_in1, 0 : i32, memref<8x4x4x1024xf32>, 4096 : i32, 1 : i32>) -> ()
// CHECK-NEXT:     %4 = arith.constant 1 : i32
// CHECK-NEXT:     "ttkernel.cb_wait_front"(%0, %4) : (!ttkernel.cb<cb_in0, 0 : i32, memref<8x4x4x1024xf32>, 4096 : i32, 1 : i32>, i32) -> ()
// CHECK-NEXT:     %5 = arith.constant 1 : i32
// CHECK-NEXT:     "ttkernel.cb_wait_front"(%1, %5) : (!ttkernel.cb<cb_in1, 0 : i32, memref<8x4x4x1024xf32>, 4096 : i32, 1 : i32>, i32) -> ()
// CHECK-NEXT:     "ttkernel.tile_regs_acquire"() : () -> ()
// CHECK-NEXT:     %6 = arith.constant 0 : i32
// CHECK-NEXT:     %7 = arith.constant 0 : i32
// CHECK-NEXT:     %8 = arith.constant 0 : i32
// CHECK-NEXT:     "ttkernel.add_tiles"(%0, %1, %6, %7, %8) : (!ttkernel.cb<cb_in0, 0 : i32, memref<8x4x4x1024xf32>, 4096 : i32, 1 : i32>, !ttkernel.cb<cb_in1, 0 : i32, memref<8x4x4x1024xf32>, 4096 : i32, 1 : i32>, i32, i32, i32) -> ()
// CHECK-NEXT:     "ttkernel.tile_regs_commit"() : () -> ()
// CHECK-NEXT:     "ttkernel.tile_regs_wait"() : () -> ()
// CHECK-NEXT:     %9 = arith.constant 0 : i32
// CHECK-NEXT:     %10 = arith.constant 0 : i32
// CHECK-NEXT:     "ttkernel.pack_tile"(%9, %2, %10) : (i32, !ttkernel.cb<cb_in2, 0 : i32, memref<8x4x4x1024xf32>, 4096 : i32, 1 : i32>, i32) -> ()
// CHECK-NEXT:     "ttkernel.tile_regs_release"() : () -> ()
// CHECK-NEXT:     %11 = arith.constant 1 : i32
// CHECK-NEXT:     "ttkernel.cb_pop_front"(%0, %11) : (!ttkernel.cb<cb_in0, 0 : i32, memref<8x4x4x1024xf32>, 4096 : i32, 1 : i32>, i32) -> ()
// CHECK-NEXT:     %12 = arith.constant 1 : i32
// CHECK-NEXT:     "ttkernel.cb_pop_front"(%1, %12) : (!ttkernel.cb<cb_in1, 0 : i32, memref<8x4x4x1024xf32>, 4096 : i32, 1 : i32>, i32) -> ()
// CHECK-NEXT:     %13 = arith.constant 1 : i32
// CHECK-NEXT:     "ttkernel.cb_push_back"(%2, %13) : (!ttkernel.cb<cb_in2, 0 : i32, memref<8x4x4x1024xf32>, 4096 : i32, 1 : i32>, i32) -> ()
// CHECK-NEXT:     func.return
// CHECK-NEXT:   }
// CHECK-NEXT: }